import { Client } from "discord.js";
import { z } from "zod";
import { ToolResponse, ToolContext, ToolHandler } from "./types.js";
import {
  loginHandler,
  setTokenHandler,
  validateTokenHandler,
  loginStatusHandler,
  logoutHandler,
  updateConfigHandler,
  healthCheckHandler,
} from "./login.js";
import { sendMessageHandler } from "./send-message.js";
import {
  getForumChannelsHandler,
  createForumPostHandler,
  getForumPostHandler,
  replyToForumHandler,
  deleteForumPostHandler,
} from "./forum.js";
import {
  createTextChannelHandler,
  createForumChannelHandler,
  editChannelHandler,
  deleteChannelHandler,
  readMessagesHandler,
  getServerInfoHandler,
  createCategoryHandler,
  editCategoryHandler,
  deleteCategoryHandler,
  listServersHandler,
  createChannelUnderCategoryHandler,
  moveChannelToCategoryHandler,
  updateServerSettingsHandler,
  updateServerEngagementHandler,
  updateWelcomeScreenHandler,
  createEmojiHandler,
  deleteEmojiHandler,
  listEmojisHandler,
  createStickerHandler,
  deleteStickerHandler,
  listStickersHandler,
  createInviteHandler,
  deleteInviteHandler,
  listInvitesHandler,
  listIntegrationsHandler,
  deleteIntegrationHandler,
  createSoundboardSoundHandler,
  deleteSoundboardSoundHandler,
  listSoundboardSoundsHandler,
} from "./channel.js";
import {
  addReactionHandler,
  addMultipleReactionsHandler,
  removeReactionHandler,
  deleteMessageHandler,
} from "./reactions.js";
import {
  createWebhookHandler,
  sendWebhookMessageHandler,
  editWebhookHandler,
  deleteWebhookHandler,
  listWebhooksHandler,
} from "./webhooks.js";
import {
  getUserInfoHandler,
  getGuildMemberHandler,
  listGuildMembersHandler,
  addRoleToMemberHandler,
  removeRoleFromMemberHandler,
  kickMemberHandler,
  banMemberHandler,
  unbanMemberHandler,
  timeoutMemberHandler,
  createRoleHandler,
  editRoleHandler,
  deleteRoleHandler,
  listRolesHandler,
  getRolePermissionsHandler,
} from "./user.js";
import { sendDirectMessageHandler, getDirectMessagesHandler } from "./dm.js";
import {
  createVoiceChannelHandler,
  deleteVoiceChannelHandler,
  editVoiceChannelHandler,
  listVoiceChannelsHandler,
  getVoiceChannelInfoHandler,
  moveUserToVoiceChannelHandler,
} from "./voice.js";

// Export tool handlers
export {
  loginHandler,
  setTokenHandler,
  validateTokenHandler,
  loginStatusHandler,
  logoutHandler,
  updateConfigHandler,
  healthCheckHandler,
  sendMessageHandler,
  getForumChannelsHandler,
  createForumPostHandler,
  getForumPostHandler,
  replyToForumHandler,
  deleteForumPostHandler,
  createTextChannelHandler,
  createForumChannelHandler,
  editChannelHandler,
  deleteChannelHandler,
  readMessagesHandler,
  getServerInfoHandler,
  listServersHandler,
  createChannelUnderCategoryHandler,
  moveChannelToCategoryHandler,
  updateServerSettingsHandler,
  updateServerEngagementHandler,
  updateWelcomeScreenHandler,
  createEmojiHandler,
  deleteEmojiHandler,
  listEmojisHandler,
  createStickerHandler,
  deleteStickerHandler,
  listStickersHandler,
  createInviteHandler,
  deleteInviteHandler,
  listInvitesHandler,
  listIntegrationsHandler,
  deleteIntegrationHandler,
  createSoundboardSoundHandler,
  deleteSoundboardSoundHandler,
  listSoundboardSoundsHandler,
  addReactionHandler,
  addMultipleReactionsHandler,
  removeReactionHandler,
  deleteMessageHandler,
  createWebhookHandler,
  sendWebhookMessageHandler,
  editWebhookHandler,
  deleteWebhookHandler,
  listWebhooksHandler,
  createCategoryHandler,
  editCategoryHandler,
  deleteCategoryHandler,
  getUserInfoHandler,
  getGuildMemberHandler,
  listGuildMembersHandler,
  addRoleToMemberHandler,
  removeRoleFromMemberHandler,
  kickMemberHandler,
  banMemberHandler,
  unbanMemberHandler,
  timeoutMemberHandler,
  createRoleHandler,
  editRoleHandler,
  deleteRoleHandler,
  listRolesHandler,
  getRolePermissionsHandler,
  sendDirectMessageHandler,
  getDirectMessagesHandler,
  createVoiceChannelHandler,
  deleteVoiceChannelHandler,
  editVoiceChannelHandler,
  listVoiceChannelsHandler,
  getVoiceChannelInfoHandler,
  moveUserToVoiceChannelHandler,
};

// Export common types
export { ToolResponse, ToolContext, ToolHandler };

// Create tool context
export function createToolContext(client: Client): ToolContext {
  return { client };
}
